version: '3.7'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - traefik-public
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
# portainer/portainer:1.23.2 fails to deploy against known external network,it's a bug!
    image: portainer/portainer:1.23.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
#    ports:
#      - "9002:9000"
    volumes:
      - portainer_data:/data
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.newproject.com`)"
        - "traefik.http.routers.portainer.entrypoints=web-secure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.docker.network=traefik-public"
networks:
  traefik-public:
    external: true

volumes:
  portainer_data: